# Profile: local
spring:
  config:
    activate:
      on-profile: local
  application:
    name: task-manager

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
# Profile: docker
spring:
  config:
    activate:
      on-profile: docker
  application:
    name: task-manager
  datasource:
    url: jdbc:postgresql://postgres:5432/taskdb
    username: taskuser
    password: taskpass
    driver-class-name: org.postgresql.Driver

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://task-manager-eureka:8761/eureka
  instance:
    prefer-ip-address: true
